package Chapter08;

public class ExceptionEx01 {
	
	public static void main(String args[]) {
		try {
			try {   } catch (Exception e) {  }
		} catch (Exception e) {
//			try {   } catch (Exception e) {  }	// 에러. 변수 E가 중복 선언되었다.
		} // try - catch 의 끝
		
		try {
		
	} catch (Exception e) {
		
	}

}
}